server:
  port:
    8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Fatsoo
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
